### ISSUE TITLE
Add changelog auto detection in workflows please

### ISSUE THREAD

**Issue by schneems** [red-data-tools/unicode_plot.rb#21]
1) Click "Actions"
2) Navigate to make a manual action
3) name the file something like "check_changes.yml" 

Put in this config:

```yml
name: Check Changelog

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check that CHANGELOG is touched
      run: |
        cat $GITHUB_EVENT_PATH | jq .pull_request.title |  grep -i '\[\(\(changelog skip\)\|\(ci skip\)\)\]' ||  git diff remotes/origin/${{ github.base_ref }} --name-only | grep CHANGES.md
```

This requires that all PRs touch the changelog or have `CI SKIP` or `CHANGELOG SKIP` in the PR title. That way your changelog is already filled out when you go to release a new version instead of having to manually go back and add it.
